apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jr5c0hb7d-go 
  janus-idp.io/tekton: jr5c0hb7d-go
  backstage.io/kubernetes-id: jr5c0hb7d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jr5c0hb7d-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  